name: ⚡️ Update Status. ⚡️
on:
  workflow_dispatch:
  schedule:
      - cron: "0 */3 * * *"
jobs:
  update-readme-with-projects:
    name: 🏃‍♂️ run the bot 🏃‍♂️
    runs-on: windows-latest
    steps:
      - uses: jainamoswal/botstatus@main
        env: # all the six environment variables are must, else the action will raise errors.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically fetched. none of business.
          BOTS: ${{ secrets.BOTS }} # link of raw file of bots in JSON format. (eg :~ https://gist.githubusercontent.com/jainamoswal/cc331a3d2a4169ab76885c5a1e076d68/raw#file-bots-json)
          SESSION: ${{ secrets.SESSION }} # telethon session string
          APP_ID: ${{ secrets.APP_ID }} # APP ID from my.telegram.org
          API_HASH: ${{ secrets.API_HASH }} # API ID from my.telegram.org
          IDS: -1001407470646:3 # Message IDs to edit.
